### PR TITLE
Create AUTHORS

### PR DESCRIPTION
**Pull request by protopopescu**
Test pull via web interface

### CODE REVIEW

**Comment by protopopescu** [comment]
This was done entirely via the web interface. We can use this method for minor changes, e.g. typos etc.

**Comment by protopopescu** [comment]
So, is this method acceptable for minor changes, e.g. typos?

**Comment by petricm** [comment]
This is the method that should be used for everything

**Comment by gaede** [comment]
The web interface should really only be used for trivial (i.e. non-code) changes, as you cannot run builds or tests before.

**Comment by protopopescu** [comment]
I agree, this is method No.2 (https://www.evernote.com/l/AJ1zG4VzUbxK0am7mm7NFjaObFX4H1VTh50) and I have another howto for method No.1 (https://www.evernote.com/l/AJ2Btx2vZn5KV67lApClST2qypmFdEhHA5k).

**Pull request merged**
